---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Setup

```{r setup}
library(targets)
library(tidyverse)

# Set the target storage folder to "_targets"
tar_config_set(store = here::here("_targets"))

source(here::here("R/functions.R"))

lipidomics <- tar_read(lipidomics)
```

## section 16

```{r}
#| eval: false
# This code was run in the console to add dependencies to the description file
usethis::use_package("stringr")
usethis::use_package("readxl")
usethis::use_package("dplyr")
usethis::use_package("tidyr")
usethis::use_package("snakecase")
usethis::use_package("here")
usethis::use_package("fs")
usethis::use_package("readr")
usethis::use_usethis()

# Then the .rprofile was edited using
usethis::use_usethis()
# and adding the following
if (interactive()) {
  suppressMessages(require(usethis))
}

# Then it was not necessary to call usethis:: so suggested packages were added like this:
use_package("usethis", "suggests")
use_package("styler", "suggests")
```

## Section 17

```{r}
#| eval: false
# create targets doc and edit the pipeline
targets::use_targets()

# run the target pipeline using
targets::tar_make()
# or use the palette (ctrl + shift + p) and search for target run

# view the visualization of the pipeline using
targets::tar_visnetwork()
# or use the palette (ctrl + shift + p) and search for target visual

# check for outdated objects
targets::tar_outdated()

# inspect targets object
targets::tar_read(lipidomics)
```

## Making a table (section 18)

```{r}
#| eval: false
lipidomics |>
  group_by(metabolite) |>
  summarise(across(value, list(mean = mean, sd = sd))) |>
  mutate(across(where(is.numeric), \(x) format(x, digits = 2))) |>
  mutate(MeanSD = glue::glue("{value_mean} ± ({value_sd})")) |>
  select(Metabolite = metabolite, "Mean ± (SD)" = MeanSD)

# lamda function \(x) alternative to function(x) and ~ with .x
# Tip! use select to rename columns
# Use glue package to paste values together
```

```{r}
#| eval: false
create_table_descriptive_stats(lipidomics)
```

## Results: basic stats table

```{r}
tar_read(table_descriptive_stats) |> knitr::kable(caption = "The mean and standard deviation of metabolites in the lipidomics dataset.")
```

Note: Some people were having problems with the %\>% pipe and tagets -
but this can be set in the \_targets file under tar_option_set(packages
= c("magrittr")

## Distribution plot

```{r}
#| eval: false
ggplot(
  lipidomics,
  aes(x = value)
) +
  geom_histogram() +
  facet_wrap(vars(metabolite), scales = "free") + # use vars() instead of ~
  theme_minimal()
```

```{r}
#| eval: false
create_plot_distributions(lipidomics)
```
